MODEL:
  NAME: "msnet_coco_rotation_30"
  META_ARCHITECTURE: "MSNet"
  BACKBONE:
    CONV_BODY: "Multi-R-18-C5"
    STOP_DOWNSAMPLING: "C3"
DATASET:
  TRAIN: "COCO_ROTATION"
  TEST: "HPATCHES_ROTATION"
  COCO_ANGLE: 30
  HPATCHES_ANGLE: 45
TRAIN:
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 200000
  BASE_LR: 1e-3
  WEIGHT_DECAY: 0.0005
  MILESTONES: [10000]
  GAMMA: 0.5
  IMS_PER_BATCH: 1
  RESUME: True
TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", 'distance', 'similarity']
    IMAGE: ['desc', 'corr', 'corr_false']
GETTER:
  NAME: 'MSNet'
