MODEL:
  NAME: "hpatches_pred"
  META_ARCHITECTURE: "MSNetV9"
  BACKBONE:
    CONV_BODY: "Multi-R-18-C5"
    STOP_DOWNSAMPLING: "C3"
DATASET:
  TRAIN: "HPATCHES_VIEWPOINT"
  TEST: "HPATCHES"
TRAIN:
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 13000
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
  MILESTONES: [10000]
  GAMMA: 0.5
  IMS_PER_BATCH: 64
TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss"]
    IMAGE: ['img0', 'img1', 'scale_pred', 'scale', 'msk']
GETTER:
  NAME: 'MSNetV9'

