MODEL:
  NAME: "matterport_coco"
  META_ARCHITECTURE: "Matterport"
  BACKBONE:
    CONV_BODY: "R-18-C5"
    STOP_DOWNSAMPLING: "C3"
DATASET:
  TRAIN: "COCO"
  TEST: "HPATCHES"
TRAIN:
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 200000
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
  MILESTONES: [10000]
  GAMMA: 0.5
  IMS_PER_BATCH: 4
TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", 'distance', 'similarity']
    IMAGE: ['desc1', 'desc2', 'img1', 'img2']
