MODEL:
  NAME: "retinanet"
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    CONV_BODY: "FPN"
DATASET:
  TRAIN: "COCO"
  TEST: "HPATCHES"
TRAIN:
  MAX_ITER: 200000
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0005
  MILESTONES: [10000]
  GAMMA: 0.5
  IMS_PER_BATCH: 4
TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss"]
    IMAGE: []
