MODEL:
  NAME: "attention_v1"
  META_ARCHITECTURE: "MSNetV5"
  BACKBONE:
    CONV_BODY: "Multi-R-18-C5"
    STOP_DOWNSAMPLING: "C3"
DATASET:
  TRAIN: "HPATCHES_VIEWPOINT"
  TEST: "HPATCHES_VIEWPOINT"
TRAIN:
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 13000
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
  MILESTONES: [10000]
  GAMMA: 0.5
  IMS_PER_BATCH: 1
TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", 'distance', 'similarity']
    IMAGE: ['desc', 'corr', 'corr_false', 'map_left', 'map_right',
        'map_left_color', 'map_right_color', 'scale', 'mask',
        'map_left0', 'map_left1','map_left2','map_left3',]
GETTER:
  NAME: 'MSNetV5'
